### ISSUE TITLE
Opening the selected folder

### ISSUE THREAD

**Issue by artyomefimov** [isabsent/FilePicker#1]
How can I open the selected folder with FOLDER_ONLY_SINGLE_CHOICE mode?

**Comment by isabsent** [comment]
`FOLDER_ONLY_SINGLE_CHOICE` will give you the opportunity to select the desired folder. After it two buttons `OPEN` and `SELECT` will appear at the bottom of the dialog. By `SELECT` button the path to the selected folder will be returned and the dialog will be closed. By `OPEN` button you will go further into the same dialog, but inside of the folder you selected.

`FOLDER_ONLY_SINGLE_CHOICE` даст вам возможность выделить выбранную папку. После выделения нужной папки внизу диалога появятся две кнопки `OPEN` и `SELECT`.  По `SELECT` вам будет возвращен путь к выделенной вами папке и диалог закроется, а по OPEN вы провалитесь дальше  - в такой же диалог, но уже в выбранной вами папке.

You can try [test apk](https://www.dropbox.com/s/ni41l7ixkh4imxh/FilePicker.apk?dl=0) with different options. 

P.S. Do not forget to use `onResult` call back.

**Comment by artyomefimov** [comment]
А как должен быть настроен SimpleFilePickerDialog?
У меня вот с этими настройками по нажатию OPEN диалог просто пропадает:

```kotlin
override fun showListItemDialog(
        titleResId: Int,
        folderPath: String?,
        mode: SimpleFilePickerDialog.CompositeMode?,
        dialogTag: String?) {
        SimpleFilePickerDialog.build(folderPath, mode)
            .title("title")
            .show(this, dialogTag)
    }
```
```kotlin
showListItemDialog(R.string.picker_name,
               Environment.getExternalStorageDirectory().absolutePath,
               SimpleFilePickerDialog.CompositeMode.FOLDER_ONLY_SINGLE_CHOICE,
               PICKER_TAG)
```
По нажатию SELECT возвращается правильный путь к выбранной папке.

**Comment by isabsent** [comment]
У меня в этом репозитории в примере `filepickerdemo` всё работает вот с таким вызовом:

        findViewById(R.id.folder_single).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                showListItemDialog(getString(R.string.dialog_title_pick_folder), rootPath, FOLDER_ONLY_SINGLE_CHOICE, PICK_DIALOG);
            }
        });

Может вы забыли о 

    @Override
    public boolean onResult(@NonNull String dialogTag, int which, @NonNull Bundle extras) {
        switch (dialogTag) {
            case PICK_DIALOG:
                if (extras.containsKey(SimpleFilePickerDialog.SELECTED_SINGLE_PATH)) {
                    String selectedSinglePath = extras.getString(SimpleFilePickerDialog.SELECTED_SINGLE_PATH);
                    Toast.makeText(this, "Path selected:\n" + selectedSinglePath, Toast.LENGTH_LONG).show();
                } else if (extras.containsKey(SimpleFilePickerDialog.SELECTED_PATHS)){
                    List<String> selectedPaths = extras.getStringArrayList(SimpleFilePickerDialog.SELECTED_PATHS);
                    showSelectedPathsToast(selectedPaths);
                }
                break;
        }
        return false;
    }

**Comment by artyomefimov** [comment]
Ок, спасибо
